#version: '3.8'

services:
  app:
    container_name: visorcam-cont
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    #command: python main.py
    image: ivisorcam